= Live C++ Coding Standards

Coding conventions, guides and standards are a perennial effort of software development. Lots of effort goes into preparing and writing them but arguably less in following them. Part of this is caused because they are usually documents relegated outside the main development work, where they evolve separately and often retroactively. 

We will show a novel model whereby the coding standard chosen by a team is a 'live' source code file integrated into a production repository and it participates in compilation. This immediately brings a couple of advantages that we will explore in detail, as well as the implications it has in the full team of developers.

As a practical example, the coding standard files of Splash Damage - a game development company - will be shown and discussed, detailing the various C++ aspects they deal with it and the techniques encouraged therein. Going further than the code, we'll talk about the human factor and how standards are written, evolved and championed across a multi-project company, each project with its own needs and constrains.

== Outline
* Standards motivation and history
* Current public examples
* Pitfalls
* The new approach
* Overview presentation of sections
* Usage in a team
* Other considerations
* In-depth presentation of sections
* Conclusions