= How to trick C++ into drawing complex GPU shaders

A tale of two systems: how to convince C++ into accepting GPU shader source code, and the graphical effects that can be written following this transformation.

Why such an effort? Having graphics code the compiles both on CPU and GPU's allows rapid prototyping, full CPU-side debugging and ground truth reference on systems where the GPU might be limited in functionality (a mobile phone for ex).

The C\++ side seems simple: most of the work is in the library that provides equivalent 2D/3D/4D vector and matrix types. What's the catch? Swizzling! The shader vector allows addressing of its components both as [0], [1], [2] etc but also as .x, .y, .xyz, .zyx, .xxx and all possible combinations. We will show how this can be achieved in modern C++, clean and in a generic way, without preprocessor tricks, and overcome language obstacles like template argument deduction with implicit conversions.

To showcase all this machinery we present Signed Distance Field modeling and a couple of visually interesting shaders that use it: Procedural Generated Planet, Volumetric Clouds simulation and some fun experiments: a Vinyl Turntable and an Egg On Bicycle!
