= Rapid Prototyping of Graphics Shaders in Modern C++ 

This talk introduces a novel technique whereby Graphics Shader language source code can be compiled as C++ in situ. There are multiple benefits for this: quick prototyping, generating reference images, testing of otherwise difficult graphical algorithms, running on less capable hardware.

On the surface of it, this is not particularly hard as the languages in question are C based, so their code can be compiled as valid C++ with a bit of library writing effort. All that's mostly needed is equivalent 2D/3D/4D vector and matrix types.

What’s the catch then? Swizzling! The shader 3D vector allows addressing of its components both as [0], [1], [2] etc but also as .x, .y, .xyz, .zyx, .xxx and all possible combinations. The talk details how this can be achieved in modern C++, clean and in a generic way, without preprocessor tricks, and overcome language obstacles like template argument deduction with implicit conversions. After all the effort it’s possible to prototype complex procedural effects at an interactive rate with full CPU-side debugging.

As takeaway and showcase of what can be achieved with the C++ techniques presented I’ll introduce Signed Distance Field functions modeling and some shaders that use it: Procedural Generated Planet, Volumetric Clouds simulation and some fun experiments: a Vinyl Turntable and an Egg On Bicycle!
